#!/bin/bash

if [ $# -eq 0 ] ; then
    echo "$(id -nu) $(id -ng) $(id -u) $(id -g)"
elif [ $# -eq 4 ] ; then
    grep -q $2 /etc/group || groupadd --gid $4 $2
    grep -q $1 /etc/passwd || useradd --uid $3 --gid $2 $1
else
    echo "usage: $(basename $0) <username> <groupname> <uid> <gid>"
    exit 1
fi

exit 0
